
set(GODOT_SYSTEM_NAME ${CMAKE_SYSTEM_NAME})
string(TOLOWER ${GODOT_SYSTEM_NAME} GODOT_SYSTEM_NAME)
string(REPLACE darwin macos GODOT_SYSTEM_NAME ${GODOT_SYSTEM_NAME})

set(GODOT_ARCH ${CMAKE_SYSTEM_PROCESSOR})
if (APPLE)
    set(GODOT_ARCH "universal")
endif ()
